source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/Arbeker01/cli-data-gem-assessment-v-000/tree/master/toy_finder" }

# Specify your gem's dependencies in toy_finder.gemspec
gemspec
